<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHPV9PI0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHPV9PI0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHPV9PI0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHPV9PI0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHPV9PI0\App_KernelDevDebugContainer([
    'container.build_hash' => 'HPV9PI0',
    'container.build_id' => 'a65adff2',
    'container.build_time' => 1618442130,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHPV9PI0');
