version: '3'

services:
    # db:
    #     image: mysql:8.0.20
    #     command: --default-authentication-plugin=mysql_native_password
    #     volumes:
    #         - "db_app:/var/lib/mysql"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #         MYSQL_DATABASE: ${MYSQL_DATABASE}
    #         MYSQL_USER: ${MYSQL_USER}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #     ports:
    #         - 3306:3306
    #     networks:
    #         - symfony
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./app/:/var/www/app/
        networks:
            - symfony
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./app/:/var/www/app/
        environment:
            DB_UPSTREAM: mysql://root:root1234@${DOCKER_GATEWAY_HOST:-host.docker.internal}:3306/contactinfo?serverVersion=5.7
        ports:
            - 8080:80
        networks:
            - symfony

volumes:
    db_app:

networks:
    symfony:
