<?php

namespace ContainerYGECYdQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SBeN3AxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SBeN3Ax' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SBeN3Ax'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'scheduleService' => ['privates', '.errored.2AH8zBX', NULL, 'Cannot determine controller argument for "App\\Controller\\ApiContactController::create()": the $scheduleService argument is type-hinted with the non-existent class or interface: "App\\Service\\ScheduleService".'],
        ], [
            'scheduleService' => '?',
        ]);
    }
}
