<?php

namespace ContainerHPV9PI0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_2AH8zBXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.2AH8zBX' shared service.
     *
     * @return \App\Service\ScheduleService
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ApiContactController::create()": the $scheduleService argument is type-hinted with the non-existent class or interface: "App\\Service\\ScheduleService".');
    }
}
