<?php

namespace ContainerHPV9PI0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactInfoTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\ContactInfoType' shared autowired service.
     *
     * @return \App\Form\Type\ContactInfoType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/ContactInfoType.php';

        return $container->privates['App\\Form\\Type\\ContactInfoType'] = new \App\Form\Type\ContactInfoType();
    }
}
